"""Sammanställer granskarens sidvisa anteckningar med den sparade crawlen."""
import json
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).parent
notes = {}

def add(path, priority, note):
    notes[path] = (priority, note)

add('/', 'P1', 'Behåll problemfokus och den visuella identiteten. Separera rutans 495 kr och provperiod från hemsidornas 12-månadersvillkor. Gör widgeten manuell. Visa produkten med ett konkret exempel före långa bevisblock. Dela FAQ efter produkt och märk kundsajternas resultat så att de inte framstår som effekt av rutan. Välj du konsekvent. Lägg till main-landmärke.')
add('/forfragningar', 'P1', 'Bra och ovanligt tydlig beskrivning av vad produkten INTE gör. Behåll den. Visa SMS och svarsförslag visuellt, en tydlig provstarts-CTA och vad nästa steg innebär. Generisk bokningshero, kontaktlänk och widget skapar för många parallella vägar. Visa månadsgränser och provperiod nära priset. Behåll pilotlägets ärlighet och förklara relationen till Invox AB begripligt.')
add('/priser', 'P1', 'Låt jämförelsen komma högre på mobil. Visa rutans pris separat från hemsidepaketen. Rätta skillnaden mellan gratis designförslag och helt färdig sajt före beslut. Byt ljus text på det gula rekommendationsmärket till mörk. Samla moms, 12 månader, första årets summa och separat annonsbudget vid korten. Ersätt uttrycket det enda som kan tillkomma med avgränsningar som stämmer med alla tjänster.')
add('/hemsida-foretag', 'P1', 'Rätta de fyra länkarna till det saknade ankaret koll-url-hero. Lägg helst förslagsformuläret på sidan. Ta bort det generella påståendet att sajter under 50 sidor är osynliga, som dessutom motsäger Bas. Tydliggör skillnaden mot webbutvecklingssidan. Använd aktuellt Spets-innehåll och en gemensam källa för priser.')
add('/tjanster', 'P2', 'Åtta tjänsteblock med många generella effekter gör valet långt. Börja med kundens behov och länka till 3 till 4 huvudvägar. Lyft in förfrågningsrutan som eget konkret erbjudande. Förtydliga att annonsbudget inte ingår i 2 990 kr, trots allt-ingår-raden. Synka uppgiften en AI SaaS-produkt mot aktuell om-sida. Minska upprepade pris- och FAQ-block.')
add('/tjanster/webbutveckling', 'P2', 'Bra kundunderlag men sidan blandar säljtext, tekniklista, prislista, två FAQ-delar och efterföljande djupdykning. Lägg projekt och leverans före verktygen. Samla FAQ. Synka prisdata centralt, avgränsa mot hemsida-foretag och rätta blandade tidslöften. Separera AI-test från Lighthouse och tona ned ovillkorliga löften om laddtid.')
add('/tjanster/managed-hemsida', 'P1', 'Konkreta driftmoment är bra. Sidan lovar genomförda ändringar inom 24 timmar på Bas-priset medan central Bas säger två arbetsdagar. Bestäm en gemensam servicenivå och skilj svar från genomförande. Visa avtalslängden nära priset. Byt managed, triage, setup och access till kundnära svenska. Samla de två FAQ-delarna och beskriv vad ett övertagande kräver.')
add('/tjanster/seo', 'P2', 'Stark idé att mäta innan du lovar. Låt leverans, nuläge och uppföljning bära sidan. Publicera metod bakom egna studier och avgränsa slutsatser om sidantal, recensionsnivåer och AI-citat. Rätta tolkningen av AI-poängen. Samla FAQ och visa tydligt skillnaden mellan audit 4 900 kr och löpande arbete i Spets.')
add('/tjanster/google-ads', 'P1', 'Förklara exakt vad 2 990 kr omfattar och varför en kampanjsida kan kosta 4 900 kr extra trots övriga sidlöften. Definiera första veckans resultat och slopa inget-spill-garantin. Skilj telefonklick från genomförda samtal. Datera Niklassons-siffrorna, förena tidshorisonterna och samla FAQ. Visa mediebudget och bindning tillsammans.')
add('/tjanster/e-handel', 'P2', 'Bra att det finns fast omfattning för större byggen. Skilj 89 000/149 000 kr-projekten och 2 495 kr drift från det mindre webbshopstillägget på 800 kr. Definiera vilka funktioner och integrationer som skiljer. Precisera gröna Core Web Vitals-garantin med metod, enhet, period och undantag. 301-planering minskar migrationsrisk men garanterar inte oförändrad ranking.')
add('/tjanster/wordpress', 'P2', 'Kortheten är bra. Visa pris, bindning och ett riktigt WordPress-exempel tidigare, inte bara i FAQ. Skilj att bygga/sköta WordPress från erbjudandet att migrera till annan teknik. Undvik att maximal säkerhet och prestanda följer automatiskt av ett ramverksbyte. Skriv WordPress konsekvent.')
add('/tjanster/ai-automation', 'P2', 'De egna produkterna är bra bevis på kompetens. Byt det tekniska kodexemplet mot ett begripligt arbetsflöde och faktisk leverans. Skilj specialbyggd automation, kalenderkopplingar och offertflöden från rutans 495 kr. Ange hur scope och fast pris bestäms. Nyansera att inga befintliga system någonsin behöver bytas.')
add('/tjanster/facebook-annonsering', 'P1', 'Sidan säger att Meta-hantering ingår i Spets, men central prislista nämner Google Ads. Beskriv gemensamt vad som faktiskt ingår, inte ett nytt paketlöfte. Ange datakälla/urval för leadkostnader eller gör dem till tydliga räkneexempel. Rätta uteslutas till exakt målgrupp och förklara målgruppsstyrning på begriplig svenska. Samla dubbla FAQ/schema.')
add('/tjanster/ai-synlighet', 'P2', 'En tydlig audit för 4 900 kr är lättare att köpa än vaga AI-löften. Ange antal frågor, AI-tjänster, körningar, datum och vad rapporten ger. Topptio-samband är eget urval, ingen generell regel. FAQ-schema utan observerad korrelation bevisar inte noll effekt. Skilj teknisk läsbarhet från verkliga omnämnanden. Samla två FAQPage-objekt.')
add('/tillganglighet', 'P1', 'Bra att du säger att automatisk skanning inte räcker. Rätta de breda lagpåståendena så att omfattning och undantag följer PTS. Redovisa Lighthouse som deltest, inte bevis på att kraven är lösta. Kontrollera uppgiften fyra hundror mot projektets faktiskt redovisade mätning. Visa momsvillkor och vad granskningen för 4 900 kr omfattar i antal mallar/flöden. Gör eget formulär tillgängligt.')
add('/sajtkoll', 'P2', 'Ett tydligt och användbart insteg. Förklara att resultatet är en teknisk snabbkontroll av testad sida, inte en full ranking-, tillgänglighets- eller AI-citeringsanalys. Harmoniera 14 kontroller här med 12 på guider-index. Undvik säker tidsutfästelse om alla målservrar kan vara långsamma. Kontrollera verklig datalagring mot integritetstexten före omskrivning.')
add('/om', 'P2', 'Porträtt, personlig kontakt och konkreta erfarenheter bör behållas. Förkorta verktygslistan och koppla bakgrunden till dagens kunder och erbjudanden. Synka 150+, hundratals och antal egna AI-produkter. Visa vad personligt ansvar innebär vid frånvaro eller brådskande hjälp om det finns ett fast arbetssätt. Undvik enterprise-jargong.')
add('/kontakt', 'P1', 'Sänk hero-höjden så formulär och direktkontakt syns tidigare. Koppla alla labels till fälten, lägg namn/e-post i en kolumn på mobil och använd autocomplete. Behåll kontaktalternativen utan att duplicera bokningsbudskap. Dölj widgetens påminnelse här. Kontrollera fel-/bekräftelselägen och Resend-leverans vid senare test.')
add('/boka', 'P1', 'Boka-länken landar på meddelandefliken. Förvälj kalendern vid bokningsavsikt och meddelandet vid kontaktavsikt. Kalenderfliken öppnades men själva bokningen testades inte. Samma etikett- och mobilkolumnproblem som kontakt. Widgetens bokningsbubbla över bokningssidan är överflödig och skymmer innehåll.')
add('/integritet', 'P1', 'Uppdatera texten mot verklig Cloudflare-/Umami-/kontakt-/AI-behandling i stället för äldre Vercel/Google Analytics-beskrivning. Klargör relationen mellan Stolt Marketing och Invox för widgeten, mottagare, lagring och rättigheter. Ta bort sälj-CTA ur juridisk sidtopp. Full juridisk revision har inte genomförts.')
add('/hantverkssajter', 'P1', 'Egen data kan bli sajtens starkaste innehåll. Redovisa population, urval, crawlperiod och att sidantal baseras på läsbara sitemaps i en mindre delmängd. Ingen chatt innebär inte att företaget bara svarar kontorstid; ingen upptäckt analytics innebär inte ingen uppföljning. Avskilj observationer från orsakspåståenden om ranking och affärer. Använd procenttalen konsekvent, exempelvis 29 procent är inte exakt en fjärdedel.')
add('/vad-kostar-en-hemsida', 'P1', 'Rätta 10 till 20 sidor för 1 190 kr mot Bas femsidesgräns. Markera marknadsintervall som uppskattningar med källa/datum, inte hela marknaden. Ta bort generella domar om DIY-ranking och 50-sidorsgränsen. Jämför samma funktioner och total kostnad över tre år. Prisguidens rådgivning ska stämma med egen abonnemangsmodell.')
add('/vad-kostar-seo', 'P2', 'Prisöversikten är användbar. Ge underlag för marknadsspannen, konkret innehåll i Spets samt moms, bindning och separat annonsbudget. Eget samband mellan sidbredd och ranking bevisar inte att länkar generellt saknar värde. Stryk att köpta länkar är det enda som kan ge bestraffning. Räkneexemplet måste skilja omsättning, marginal och faktisk avkastning.')
add('/sokmotoroptimering', 'P1', 'Publicera metod bakom egna 201 träffar, fem branscher och AI-citat. Nyansera 50-sidorsgräns, recensions-trösklar, obligatoriskt ordantal och topptio-krav för AI. Skilj korrelation från orsak. Canonical är en signal, inte en säker raderingsknapp. Behåll pedagogisk struktur men ersätt absolut språk med kontrollerbara slutsatser och faktiska exempel.')
add('/projekt', 'P2', 'Gör urvalet lättare: visa ett fåtal relevanta projekt med bransch, uppdrag och belagt resultat, sedan fler. Nu blandas appar, utbildning, lokala företag och stora teknikförklaringar. Förkorta varje kort och flytta detaljer till caset. Synka perioder och definitioner med startsidans statistik. Standardisera mätkort och bildformat.')
add('/projekt/niklassonsflytt', 'P1', 'Bra case för målgruppen. Samordna projektindexets 37, casets 32 och startsidans rullande tal genom tydliga datum, inte genom att välja högsta talet. Historiska värden ska inte heta senaste 30 dagarna. Visa källa och skilj förfrågningar/telefonklick från kunder. Lyft kundnyttan och skärmbilder före tekniken.')
add('/projekt/arkipel', 'P1', '61 sidor jämförs med 17 som är branschmedian, inte nödvändigtvis kundens gamla sajt. Märk jämförelsen korrekt. Tekniska värden som serversvar och sidvikt behöver mätdefinition; de bevisar inte i sig mer organisk trafik. Byt branschsnitt kontra god till jämförbara före/efter-mått. Visa det faktiskt levererade innehållet.')
add('/projekt/ngtab', 'P2', 'Den tekniska berättelsen kan kortas till problem, åtgärd och kundeffekt. Beskriv canonical-felet som en risk och ange observerad effekt bara där den är mätt. Sidantal i sig bevisar inte nya kunder. Lägg faktiska skärmbilder, serviceområden och kontaktflöde före kodnära resonemang.')
add('/projekt/premiebygg', 'P2', 'Förklara vilket kundproblem som verkligen fanns före bygget och skilj det från generella formrisker. 88 ms serversvar och komprimerade bilder är olika delar av laddningen. 100 i SEO-test är inte samma sak som ranking. Använd daterade kontaktresultat och tydligt före/efter som går att jämföra.')
add('/projekt/linguista', 'P1', 'Separera AI-läsbarhet från Lighthouse-kategorier. 50 poäng bevisar inte att halva innehållet var oläsbart, och 82/100 tillgänglighet innebär inte per automatik lagbrott. Bevara datum och enhet för mätningarna. Lyft redaktörernas arbetsflöde och visa hur det fungerar i stället för att låta poänggrafiken bära allt bevis.')
add('/projekt/edshare', 'P1', 'Samma åtskillnad mellan Lighthouse, AI-test och juridisk tillgänglighet behövs här. Visa bara faktiskt uppmätta före-/eftertal; interpolerade siffror från en slider ser ut som mätresultat trots att de är animation. Definiera vad 86 procent lägre vikt omfattar. Redaktörens nya arbetsflöde är starkare kundbevis än ramverksnamnet.')
add('/projekt/batteriproffs', 'P2', 'Bra med verklig försäljning och att det är ett eget projekt. Ange vilken första månad som avses och hur Google/ChatGPT-attribution fastställdes. Fem beställningar är ett litet urval, inte en generell tillväxtgaranti. Datera Lighthouse-testet. Visa produktval och checkout visuellt.')
add('/projekt/forskolan-harpan', 'P3', 'Kort och relevant text om föräldrarnas behov. Ingen anledning att fylla ut för ett visst ordantal. Komplettera med tydliga skärmbilder och ett konkret exempel på hur personalen uppdaterar innehållet. Kontrollera aktualiteten i verksamhetsuppgifter som antal barn. Gör nästa steg specifikt för liknande verksamheter.')
add('/projekt/pingstkyrkan', 'P3', 'Tydligt vardagsproblem: besökare behöver tider och information. Visa hur startsida, kalender och kontakt löser det på mobil samt vem som uppdaterar. Behåll kortheten. Lägg till faktiska resultat endast om de finns, inte konstruerade effektmått.')
add('/projekt/gardetshundtrim', 'P3', 'Bra branschspecifik beskrivning. Visa tjänste/pris- och bokningsflödet i stora bilder. Förklara vem som kan ändra innehållet och vad kunden fick levererat. Behöver mer konkret bevis, inte fler generella SEO-stycken.')
add('/guider', 'P2', 'Bra uppdelning i praktiska guider. Rätta 12 kontroller till samma faktiska antal som sajtkollen. Recensionsbeskrivningen ska inte lova att recensioner ensamma avgör kartplacering. Lägg författare och senaste faktakontroll tydligt på guiderna.')
add('/guider/chatgpt-for-smaforetag', 'P2', 'Användbara uppgifter och promptidéer. Placera instruktionen om att anonymisera kundmaterial före första rådet att klistra in ett kundmejl eller en hel tråd. Skilj konsumentkonto från godkänt företagsverktyg med relevanta villkor. Ett korrekt testsvar bevisar inte att verktyget är tillförlitligt generellt. Lägg kopierbara exempel och testa aktuell produktinformation vid nästa uppdatering.')
add('/guider/fler-google-recensioner', 'P1', 'Rätta hänvisningen till marknadsföringslagen 12 c §; den säger inte det generella rabattförbud som anges. Skilj lag från Googles incitamentspolicy. Ta bort selektionssteget där bara nöjda kunder ska tillfrågas, som motsäger guidens egen varning. Nyansera att recensioner avgör placering och använd ett neutralt exempel på förfrågan till alla verkliga kunder.')
add('/guider/synas-i-ai-sok', 'P2', 'Bra att ett enstaka eget kundexempel inte presenteras som stort bevis. Behåll det. Nyansera resten av de generella påståendena om vad alla AI-motorer föredrar, schema och att resten följer av sig självt. Beskriv repeterbar testmetod över flera körningar och tjänster. Eget frånvaro-av-samband för FAQ-schema är inte universellt facit.')
add('/blogg', 'P2', 'Prioritera kvalitet framför 32 jämnstora kort. Ge ämnesfilter och 3 till 5 rekommenderade startpunkter. Visa vad läsaren får ut, senaste faktakontroll och konsekvent författare. Beräkna lästid från verklig textlängd; flera korta artiklar anges som 9 till 11 minuter. Separera köpguider från allmän inspiration.')
add('/lp/hemsida-foretag', 'P1', 'Behåll det fokuserade formulärflödet och avsiktlig noindex. Datera 37-förfrågningsbeviset och rätta färdig-hemsida-löftet till förslagets verkliga omfattning. Synka supportnivå och Spets med central prislista. Ta bort dubbleringen 800 kr/mån som tillägg. Villkor och export av sajt bör förklara vad som händer med funktioner, inte bara filer.')
add('/lp/wordpress', 'P2', 'Bra att hjälpen även gäller sajter byggda av andra och att WordPress kan behållas. Tydliggör säkerhetsgenomgång kontra offentligt prestandatest: plugins och backuper kan inte granskas fullt utan åtkomst. Synka 24 timmar/samma arbetsdag och Bas-villkor. Definiera sidvikt och mätning bakom 86 procent. Bevara noindex om sidan används som annonslandning.')
add('/serviceavtal', 'P2', 'Ett eget större förvaltningsupplägg kan vara rimligt, men Bas 2 000 kr och svarstid 2 till 14 dagar ska tydligt skiljas från sajtens Bas 1 190 kr. Märk målgrupp och avtalets omfattning. Förklara outnyttjade timmar, extra arbete och vad jour innebär. Behåll noindex för direktdelning. Lägg main och undvik den globala chatbotens andra prisbild på avtalet.')

blog = {
'ai-for-foretag': ('P1','Skriv om från grunden. Rätta bland annat retta, sparer och innehål. Belägg eller stryk 40 procent fler leads och de säkra tidsvinsterna. Skilj egna kundcase från exempel och beskrivet AI-stöd från automatiskt ansvar. Undvik svepande påståenden om vad AI aldrig eller alltid klarar.'),
'ai-verktyg-smaforetag': ('P2','Titeln lovar tolv verktyg men listan innehåller flera allmänna arbetsuppgifter/kategorier. Byt till tolv användningar eller namnge faktiskt testade verktyg med datum och kostnadsnivå. Särskilj från ChatGPT-guiden och AI-automationsartikeln. Kortare introduktion och mer konkreta exempel.'),
'automatisera-med-ai': ('P2','Bra konkreta flöden och mänsklig kontroll. Skilj regelstyrd automation från AI så att vanliga kalender- och fakturaflöden inte säljs som AI per automatik. Märk tidsvinster som antaganden om de inte är uppmätta. Länka rätt till rutans standardprodukt respektive specialbygge.'),
'betallosningar-webbutik': ('P2','Behåll jämförelsen och tydliga räkneexempel. Rätta resonemanget om procentavgifter: procentandelen är konstant, medan en fast avgifts andel sjunker med ordervärdet. Ange leverantör, plan och datum för avgifter. Skilj Swish Handel och betalförmedlare. Optimera inte mot det irrelevanta databasordet tar normal swish.'),
'chatbot-for-foretag': ('P2','Titeln lovar kostnad men svaret blir för allmänt. Visa ditt verkliga 495-kronorserbjudande, gränser och vad som kostar separat. Håll kalenderbokning, telefonsvar och inkorgsintegration isär från standardrutan. Ett extra jobb täcker inte alltid kostnaden: räkna på marginal, inte hela ordervärdet.'),
'checklista-ny-hemsida': ('P2','Bra användbar checklista. Gör punkterna möjliga att bocka av eller skriva ut och länka till riktiga testverktyg. Uppdatera gammal hänglåsbeskrivning och nyansera canonical, noindex och 301. Ta inte cookiekrav som universellt utan att beskriva faktisk teknik. Ett fungerande formulär ska verifieras hos mottagaren.'),
'content-strategi-smaforetag': ('P1','Redaktionell omskrivning behövs. Språkfel som invest ererar, Anvand, best och subscribers stör förtroendet. Stryk generella garantier om 3 till 5 gånger trafik, minimiordantal och nästan säkert rankande prisguider. Visa en riktig liten innehållsplan med sökintention, prioritet, exempel och uppföljning.'),
'e-handel-guide': ('P1','Rätta momsgränsen omgående och kontrollera alla ekonomiska uppgifter. Stripe-priset är inte dagens generella svenska avgift. Belägg påståendet att ni hjälper hundratals e-handlare. Ta bort den generiska försäljningsprognosen månad för månad. Skilj utbetalningstid, kundens betalning och vinst. Språk och struktur kräver en full omskrivning.'),
'e-postmarknadsforing-smaforetag': ('P2','Bra praktiskt välkomstflöde. Ta bort att mejl når allas inkorg varje gång och alltid är gratis. Nyansera juridik om kontaktlistor och uppföljning utifrån situationen. Förklara att öppningsgrad påverkas av integritetsskydd och att klick/köp väger tyngre. Testa frekvens; hävda inte att folk sällan avprenumererar på grund av många mejl.'),
'google-ads-byra-eller-sjalv': ('P2','Relevant befintlig söksynlighet. Länken till Ads-tjänsten finns redan högt och ska behållas. Lägg till tydligare beslutsjämförelse och konkret leverans för ditt upplägg. Ange källa/urval för 20 till 50 procent bortkastad budget. Nyansera antaganden om Googles avsikt. Undvik att varna generellt för den bindning som ditt eget erbjudande har.'),
'google-ads-vs-seo': ('P1','Rätta plöckföretag, lokaltjänsteman och kostnad per kunskap. Håll trafik, kontakter, kunder och marginal isär i prognosen. Exakta intäkter över sex/tolv månader ska vara scenarier, inte förväntat normalutfall. Påstå inte att SEO-positionen består när arbetet upphör eller att dagsbudget är ett ovillkorligt dagstak.'),
'google-business-profile-guide': ('P1','Faktagranska statistik och verifieringsmetoder mot aktuell Google-hjälp. Ta bort påhittade kategorier som Nödemergency-tjänst och Buskehållsservice. Förklara serviceområdesföretag och adress korrekt. Recensioner är inte enda rankingfaktorn. Rätta blandat språk och ersätt 10 till 30 förfrågningar/månad som generellt löfte med ett verifierat case eller tydligt exempel.'),
'hemsida-inga-kunder': ('P2','En av de mer användbara problemguiderna. Prioriteringsordningen och kontaktchecken är bra. Gör en kort självdiagnos tidigt och minska överlapp med konverteringsartikeln. Underbygg procentsatser/tidsgränser för avhopp. Föreslå mätning som skiljer formulärleverans, kvalificerad kontakt och affär.'),
'hemsida-som-saljer': ('P1','Rätta räknefelet: 1 000 besökare gånger 5 procent ger 50 leads, varav 7 procent är 3,5, inte 35. Rätta innehål, övertyg kraft, spesifik och direktöversatta uttryck. Stryk universella effektlöften. Ge ett verkligt före/efter-exempel och särskilj från de andra konverteringsguiderna.'),
'konverteringsoptimering-tips': ('P2','Bra och handlingsbar struktur. Nyansera att alla ändringar är gratis efteråt och att varje fält alltid kostar svar. En före/efter-jämförelse påverkas av säsong och trafikmix; beskriv begränsningen. Lägg till mätbara hypoteser och skilj formulärhändelse från faktiskt mottaget lead.'),
'landningssida-som-konverterar': ('P2','Behåll matchningen mellan annons och erbjudande och checklistan. Visa en riktig kommenterad landningssida. Stryk ospecificerade 80-procentspåståendet om rubriken. Ingen meny och exakt en CTA är en användbar hypotes för vissa kampanjer, inte en regel för alla köp. Ge utrymme för förtroende, villkor och kundens behov.'),
'lokal-seo-guide': ('P1','Stor omskrivning. Ta bort det ryska Включи, HTML-entiteter och språkfel. Rätta förenklade instruktioner om verifiering/kategorier. Versaler i företagsnamnet gör inte automatiskt samma firma till tre företag hos Google. Belägg eller ta bort 80-procentspåståendet och 40 till 100 procent fler bokningar. Utgå från relevans, avstånd och kändhet.'),
'marknadsforing-smaforetag': ('P2','Bra princip att fokusera på få kanaler och följa verkliga förfrågningar. Lägg ett konkret svenskt exempel med budget och avgränsningar. Nyansera att små annonsbudgetar alltid är bortkastade och att vissa branscher generellt inte har nytta av sociala medier. Be om recensioner enligt en neutral rutin, inte selektivt bara från nöjda kunder.'),
'moms-regler-e-handel': ('P1','Uppdatera livsmedelsmoms från gamla 12 procent till aktuell hantering från april 2026. Rätta påståendet att även alla små aktörer måste momsregistreras och beskriv villkor för undantag med källa. Nyans behövs för ångerrättens undantag, OSS och producentansvar. Ta bort trygghetslöftet att checklistan räcker juridiskt för en vanlig butik. Datera granskningen.'),
'seo-analys-sjalv': ('P2','Bra fokus och relevant söksynlighet. Gör checklistan användbar och lägg ett faktiskt analysutdrag. Site-sökningens träffantal är inget tillförlitligt inventeringsmått; använd Search Console/URL-inspektion för slutsatser. Skilj snabb 30-minuterskontroll från komplett audit. Nya Search Console-konton får inte omedelbart full historik. Rätta den oproportionerliga lästiden.'),
'seo-for-smaforetag': ('P2','Bra nybörjarstruktur men föråldrade verktygsråd och hårda regler behöver bort. Mobile-Friendly Test är nedlagt. 60/160 tecken och 300 ord är inte obligatoriska SEO-gränser. Recensionstal och betyg garanterar ingen placering. Visa källor och dela tydligt upp mot 17 SEO-tips och huvudguiden.'),
'seo-tips-smaforetag': ('P2','Kort och överblickbar. Påstå inte att färskt innehåll alltid rankar bättre; uppdatera när det förbättrar korrekthet/relevans. Nyansera de kategoriska lokala rankingpåståendena. Ge tipsen exempel eller verktyg så de tillför något utöver sju-stegsartikeln. Planera eventuell sammanslagning först med query-/URL-data.'),
'sokordsanalys-nyborjare': ('P2','Bra förklaring av intention och ämnesgrupper. Google kan förstå synonymer, så det är för starkt att säga att inga kundord ger inget att matcha mot. Autocomplete är inte en exakt volymrangordning. Två liknande sidor tappar inte automatiskt båda. Visa ett verkligt litet sökordsurval med källa, datum och sidkarta.'),
'teknisk-seo-guide': ('P2','De aktuella CWV-trösklarna är rätt här. Rätta löftet om FAQ-utökningar i Google, och nyansera canonical samt noindex/robots. Självrefererande canonical är inte rätt för varje duplicerad variant. WWW är ett val, inte generellt bättre SEO. Gör checklistan användbar och lägg INP även i slutsammanställningen.'),
'vad-kostar-google-ads': ('P1','Bra uppdelning av mediebudget, arvode och kringkostnader. Rätta slutsatsen att 48 000 kr intäkt efter 6 000 kr annonser är tydlig vinst; den kräver täckningsbidrag och alla kostnader. 15 leads gånger 25 procent blir 3,75 förväntade kunder, vilket bör framgå som scenario. Datera och belägg branschernas klickprisintervall. Befintlig synlighet gör denna viktig.'),
'vad-kostar-webbutik': ('P2','Behåll kostnadsuppdelningen och treårsresonemanget. Datera plattforms-, betal- och fraktintervall och länka till källor. Skilj löpande plattformsavgift från engångsuppsättning. Visa hur ditt 800-kronorstillägg respektive större e-handelsbygge passar in, utan att låtsas att alla upplägg har samma omfattning.'),
'valja-domannamn': ('P2','Bra råd om ägande, förnyelse och telefontest. Rätta att ett domänbyte alltid nollställer SEO; en korrekt migration kan överföra signaler men innebär risk och variation. En .se-domän bevisar inte i sig att innehavaren är svensk eller följer svensk lag. Skilj domäninnehavare från administratörens konto.'),
'valja-seo-byra': ('P1','Texten motarbetar ditt eget erbjudande: under 3 000 kr kallas sällan seriöst, 12 månader kritiseras och avslutningen lovar arbete utan bindning. Ditt Spets kostar 2 990 kr med 12 månader. Skriv om kring konkret leverans, ägande, uppföljning och rimlig omfattning. Bevara varningen mot garanterad förstaplats.'),
'varfor-snabb-hemsida': ('P1','Skriv om från grunden. FID är föråldrat och Google visar inte generellt den beskrivna gröna/gula hastighetsmarkeringen i sök. Slutledningen 1 000 besökare till 260 förlorade kunder blandar besök med kunder. Rätta språkfel och källbelägg eller stryk de uppräknade effekttalen. Tekniknamn garanterar inte snabbhet.'),
'webbdesign-trender-2026': ('P1','Rubriken lovar aktuellt omdöme men texten innehåller språkfel, fel INP-gräns och alltför breda lag-/hälsopåståenden. 16 px är ingen allmän WCAG-minimiregel. Dark mode är inte automatiskt mer tillgängligt. Rätta Nästa.js. Skriv en egen välgrundad genomgång med riktiga exempel och praktiska avvägningar.'),
'wordpress-eller-webbyra': ('P1','Titelns jämförelse är felställd: en webbyrå kan bygga WordPress. Döp om till bygga själv eller anlita hjälp och jämför lika omfattning. Rätta kostnadstabellen, språk och ROI-påståendet om återbetalning vecka två. Nyansera SSL-kostnad, säkerhet och underhåll. Redovisa egna priser utan att svartmåla alternativ.'),
'wordpress-vs-nextjs': ('P1','Behåll att valet beror på behov, men resten måste följa samma saklighet. Universella laddtider och Lighthouse-intervall per ramverk saknar underlag. Next.js är inte alltid statisk HTML, underhållsfritt eller utan databas. Skilj implementation från plattform och visa redaktörsbehov, integrationer, ägande och total driftkostnad.'),
}
for slug, (priority, note) in blog.items():
    add('/blogg/'+slug, priority, note)

city_notes = {
'hassleholm': {
'': 'Din verkliga bas är en tillgång. Visa konkreta lokala projekt och mötesmöjlighet. Knyt inte erbjudandet till osäker framtida höghastighetsjärnväg. Skilj grundläggande SEO från aktiv optimering i prisangivelsen.',
'hemsida': 'Använd lokalt case och faktisk arbetsprocess. Rensa allmän stadshistoria och osäkra infrastrukturlöften. Beskriv fem sidor kontra Bredd och visa relevant förslag direkt.',
'seo': 'Kundens sökord blandas ihop med webbyrå Hässleholm. Byt till kundens tjänst plus ort och visa ett verkligt dataexempel. Belägg påstådd låg konkurrens i rätt bransch.',
'google-ads': 'Rätta Det allra flesta. Låg geografisk konkurrens innebär inte automatiskt billig eller lönsam annonsering. Visa ett scenario med klickpris, konvertering och marginal samt separat mediebudget.',
'ai-automation': 'Utgå från ett konkret lokalt arbetsflöde, inte AI i allmänhet. Håll specialintegrationer och kalenderbokning isär från standardrutan. Visa vad analys och fast pris omfattar.'},
'kristianstad': {
'': 'Rätta biofärreseratet och kontrollera de listade orternas relevans för serviceområdet. Visa verklig närvaro och kundnytta i stället för geografisk utfyllnad. Förklara vad SEO från 1 190 faktiskt innebär.',
'hemsida': 'Visa rätt kundtyp, innehållsomfattning och ett verkligt projekt. Undvik utbytbara stadspresentationer. Förankra lokala erfarenhetsanspråk och länka till bevis.',
'seo': 'Rätta exemplet där en kund förväntas synas på webbyrå-sökningen. Använd kundens bransch och verifierad sökdata. Prioritera faktisk lokal efterfrågan framför många ortsord.',
'google-ads': 'Förklara serviceområde och hur irrelevanta förfrågningar följs upp utan att lova noll spill. Gör mediebudget och förvaltningsavgift tydliga. Ersätt generella stadspåståenden med ett relevant scenario.',
'ai-automation': 'Beskriv en avgränsad process och hur resultatet mäts i tid eller färre manuella steg. Skilj engångsbygge, drift och rutans standardpris. Kundspecifika system kräver verklig behovsanalys.'},
'helsingborg': {
'': 'Ge ortshubben ett annat syfte än /hemsida. Visa hur du arbetar från Hässleholm med kunder här. Rangordna huvudtjänsterna och undvik SEO-ingår-formulering som ser ut som löpande arbete i Bas.',
'hemsida': 'Sidan har observerad synlighet för webbyrå Helsingborg. Bevara adressen tills Search Console motiverar annat. Lägg verkligt case, konkret omfattning och rätt pris tidigt; minska generiska ortsstycken.',
'seo': 'Påståendet att handeln utgör ungefär halva stadens ekonomi behöver källa eller kan tas bort. Det hjälper inte köparen välja SEO. Visa relevanta sökningar, nuläge och vad som levereras varje månad.',
'google-ads': 'Förklara hur annonseringen matchar tjänst och område och vad som mäts som lead. Priskorten ska handla om Ads-upplägget, inte bara en ny webbplats. Inga geografiskt härledda lönsamhetslöften.',
'ai-automation': 'Ge en konkret process före teknikorden och visa var människan godkänner. Särskilj standardrutan, integration och specialbygge. Ange vilka underlag som behövs för fast pris.'},
'malmo': {
'': 'Rätta Malmö-baserad och Baserad i Malmö till korrekt utgångspunkt Hässleholm. En storstadstext får inte uppfinna lokal etablering. Visa faktiska projekt eller tydlig arbetsmodell för Malmö.',
'hemsida': 'Rätta lastar snabbt till laddar snabbt. Minska agencypriser, polish och andra blandade uttryck. Förklara omfattning och pris. Behåll direktkontakt som styrka utan påhittad lokal adress.',
'seo': 'Stadens konkurrensbild måste kopplas till kundens tjänst och uppmätta sökord. Ett brett påstående om Malmö ger ingen prioritering. Visa konkret leverans och korrekt skillnad mellan grund och aktiv SEO.',
'google-ads': 'Förklara targeting/ROAS om begreppen behövs, annars använd räckvidd, rätt förfrågningar och lönsamhet. Visa tydligt arvode och mediebudget. Exakt rätt målgrupp eller noll spill är inte garantier du kan ge.',
'ai-automation': 'Ett lokalt ortsnamn gör inte AI-lösningen särskild. Visa verklig process, exempel, integrationer och avgränsningar. Separera standardproduktens 495 kr från offert på specialarbete.'},
'lund': {
'': 'Verifiera påstådd erfarenhet från Ideon med namngivet projekt eller tona ned. Stadens kunskapsprofil ersätter inte egen referens. Kontrollera områdeslistans relevans. Skilj hubben från /hemsida innan större SEO-ändringar.',
'hemsida': 'Påståendet att många kunder finns inom tech/life science behöver stöd. Minska stereotyper om att Lundakunder läser källkod lika gärna som copy. Visa leverans, konkret projekt och fungerande redaktörsflöde.',
'seo': 'Förklara vilka kunder och sökningar som avses, inte generisk akademisk profil. Koppla egen data till ett relevant exempel. Visa avgränsat SEO-erbjudande och nollmätning.',
'google-ads': 'Förklara kvalificerade förfrågningar och hur lokala respektive bredare B2B-sökningar skiljs åt. Minska teknik- och startup-jargong och synka pris, annonsbudget och villkor.',
'ai-automation': 'Beskriv ett konkret arbetsflöde för den avsedda köparen och visa faktisk kompetens. Underbygg branscherfarenhet. Skilj kalender-/systemintegration och offertautomation från den mindre förfrågningsrutan.'},
}
shared = ' Gemensamt för ortsmallen: korta ned generisk text, samla FAQ, använd rätt tjänstepris och undvik att skriva fler ord utan nytt kundvärde.'
for city, entries in city_notes.items():
    for slug, note in entries.items():
        path='/'+city+('/'+slug if slug else '')
        priority='P1' if path in ['/malmo','/hassleholm/seo','/kristianstad/seo'] else 'P2'
        add(path,priority,note+shared)

pages=json.loads((ROOT/'crawl.json').read_text())
checks={x['path']:x for x in json.loads((ROOT/'checks.json').read_text())['checks']}
paths=[urlparse(p['url']).path.rstrip('/') or '/' for p in pages]
assert len(paths)==100 and len(set(paths))==100
assert set(paths)==set(notes), (set(paths)-set(notes),set(notes)-set(paths))
out=['# Sidvis genomgång: 100 publika sidor', '',
     'Granskad 4 oktober 2026. Läs RAPPORT.md för metod, gemensamma komponentfel, källor och begränsningar. Varje rad nedan är en redaktionell åtgärd efter genomläsning; en P1/P2/P3 är prioritet, inte ett SEO-poängtal.', '',
     'P1: rätta fel, motsägelser eller viktig kontaktfriktion. P2: förbättra tydlighet, innehåll och struktur. P3: komplettera en i huvudsak fungerande sida. Ordantal avser crawlens extraherade huvudtext och är endast orientering, aldrig ett rekommenderat minimiantal.', '']
for p,path in zip(pages,paths):
    pri,note=notes[path]; c=checks[path]
    flags=[x for x in c['issues'] if x not in ('TWITTER_HOME','MISSING_CANONICAL')]
    extra=' Teknisk notering: '+', '.join(flags)+'.' if flags else ''
    out += [f'## {path}', '',f'[{p["title"]}]({p["url"]})', '',f'**{pri} · HTTP {p["status"]} · cirka {c["words"]} ord.**{extra}', '',note,'']
(ROOT/'SIDOR.md').write_text('\n'.join(out))
print(f'Skapade SIDOR.md med {len(paths)} granskade URL:er.')
