"use client";

import { PageHero } from "@/components/ui";

const sections = [
  { title: "Ansvar och kontakt", paragraphs: ["Joel Stolt, Stolt Marketing i Hässleholm, ansvarar för hur uppgifter som du lämnar på stoltmarketing.se används för kontakt och kundrelationer. Frågor om personuppgifter, registerutdrag och radering skickas till joel@stoltmarketing.se.", "Den här informationen gäller Stolt Marketings egen webbplats. Om du som företag köper förfrågningsrutan regleras hanteringen av dina kunders uppgifter i det separata avtalet och personuppgiftsbiträdesavtalet för Kvota Kundkontakt."] },
  { title: "När du skriver eller bokar", paragraphs: ["Kontaktformuläret tar emot ditt namn, din e-postadress och ditt meddelande. Företagsnamn, webbadress eller andra uppgifter kan finnas i den text du lämnar. Kontaktwidgeten kan även ta emot telefonnummer, chattmeddelanden och önskemål om uppringning. Bokningskalendern tar emot de uppgifter som efterfrågas i Googles bokningsflöde.", "Uppgifterna används för att besvara din fråga, följa upp en begäran, förbereda en offert eller hantera en bokning. När du själv vill ingå avtal används uppgifterna för åtgärder före avtal och för att fullgöra avtalet. Övrig företagskontakt hanteras med stöd av intresset av att kunna besvara relevanta affärsförfrågningar. Formuläret innebär inte ett samtycke till nyhetsbrev eller reklam."] },
  { title: "Kontaktverktyg och AI", paragraphs: ["Meddelanden från kontaktformuläret sparas först i en leveranskö på Cloudflare och skickas vidare till Kvota Kundkontakt samt till Joel via e-posttjänsten Resend. Kvota samlar ärendet och kan bearbeta innehållet med AI för att ta fram ett svarsförslag. Joel granskar svaret innan det skickas.", "Kontaktwidgeten är Svarslagret från Invox AB. AI-chatten i widgeten svarar automatiskt och kan spara samtalshistorik så att dialogen går att fortsätta. Funktionen Frågor om din sajtkoll skickar ditt meddelande och sajtkollens sammanhang till Anthropic för att skapa ett svar. Skriv inte känsliga personuppgifter, personnummer, lösenord eller uppgifter om andra som inte behövs för din fråga.", "AI-svar kan bli fel. Inga köp, avtal eller beslut om dig fattas enbart av AI på den här webbplatsen. Du kan alltid kontakta Joel direkt via e-post eller telefon."] },
  { title: "Besöksstatistik, drift och annonser", paragraphs: ["Webbplatsen levereras genom Cloudflare. Tekniska uppgifter, exempelvis IP-adress och uppgifter om enheten, behandlas för att leverera sajten, begränsa spam och hantera fel. Ändamålet är en fungerande och säker webbplats.", "Besöksstatistik samlas med Umami, vars statistikinstallation körs på Vercel. Statistiken används för att förstå vilka sidor och kontaktvägar som fungerar. Sajten använder inte Google Analytics. Umamis statistikskript använder inte analyscookies.", "Kommer du från en annons kan annonsens klick-id finnas i adressen. Sajten håller det tillfälligt i den öppna sidans minne och kan skicka det tillsammans med en formulärförfrågan för konverteringsmätning i Google Ads. Det sparas inte av sajten i en cookie. Det är skilt från meddelandets innehåll och används för att följa upp annonsernas resultat."] },
  { title: "Lagring i webbläsaren och externa tjänster", paragraphs: ["Kontaktwidgeten använder webbläsarlagring för funktioner som öppet eller stängt läge, utkast och fortsatt chatt. Den laddar kontaktfunktionerna när du väljer att öppna rutan. Sådan funktionslagring är skild från Umamis besöksstatistik.", "På bokningssidan bäddas Google Kalender in. Google får då tekniska uppgifter från webbläsaren och behandlar bokningsuppgifter när du använder kalendern. Du kan i stället skicka ett vanligt meddelande eller mejla Joel."] },
  { title: "Leverantörer och överföring utanför EU/EES", paragraphs: ["De centrala tjänsterna är Cloudflare för webbplats, lagring och skydd; Resend för e-post; Svarslagret från Invox AB för kontaktwidgeten; 46elks för SMS och telefoni i kontaktwidgeten; Kvota Kundkontakt för kontaktärenden och svarsförslag; Anthropic för AI; Umami på Vercel för besöksstatistik; samt Google för bokning och annonsmätning. Vilka tjänster som tar emot dina uppgifter beror på vilka funktioner du använder.", "En del av bearbetningen sker hos leverantörer i USA. EU-baserad datalagring innebär därför inte att all behandling sker inom EU. Leverantörernas dataskyddsvillkor och underbiträden styr de enskilda överföringarna. Kontakta Joel för information om aktuella mottagare, avtal och vilka överföringsskydd som gäller för ditt ärende. Uppgifter säljs inte."] },
  { title: "Hur länge uppgifterna behövs", paragraphs: ["Kontaktuppgifter och korrespondens behövs medan förfrågan hanteras och för relevant uppföljning. Om kontakten leder till ett uppdrag kan delar behövas under kundrelationen och för att uppfylla avtals- eller lagkrav. Lagringstiden beror alltså på ärendet och dess fortsättning; radering av ett meddelande i ett system innebär inte automatiskt att alla leverantörers säkerhetskopior försvinner samma dag.", "Den tekniska leveranskön på webbplatsen rensar normalt färdigbehandlade poster efter 30 dagar. Det är en kö för säker leverans, inte ett löfte om att kundärendet och mejlet raderas efter 30 dagar. För uppgift om vad som finns sparat i ditt ärende eller begäran om radering, kontakta Joel."] },
  { title: "Dina rättigheter", paragraphs: ["Du kan begära information och tillgång till dina uppgifter, rättelse, radering och begränsning av behandlingen. Du kan invända mot behandling som grundas på berättigat intresse. Rätt till dataportabilitet gäller när förutsättningarna i dataskyddsförordningen är uppfyllda. Rättigheterna kan begränsas av exempelvis lagkrav och behovet att hantera rättsliga anspråk.", "Mejla joel@stoltmarketing.se så hjälper jag dig. Du har också rätt att lämna klagomål till Integritetsskyddsmyndigheten, IMY."] },
];

export default function IntegritetContent() {
  return <><PageHero compact cta={false} breadcrumbs={[{ label: "Start", href: "/" }, { label: "Integritet" }]} badge="Personuppgifter" title="Så används dina uppgifter" subtitle="Här beskriver jag vad som händer när du besöker sajten, skriver ett meddelande, använder AI-chatten eller bokar en tid. Uppdaterad 4 oktober 2026." />
    <section className="px-5 sm:px-8 py-10 sm:py-14"><div className="article-body mx-auto">{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mb-5">{paragraph}</p>)}</section>)}<p className="mt-8"><a href="https://www.imy.se/privatperson/dataskydd/dina-rattigheter/" className="text-primary underline">Läs om dina rättigheter hos IMY</a>.</p><p className="mt-5"><a href="mailto:joel@stoltmarketing.se" className="text-primary underline">Kontakta Joel om personuppgifter</a>.</p></div></section>
  </>;
}
