import { packages } from "@/lib/pricing-packages";

const h = (text) => ({ type: "h2", text });
const p = (text) => ({ type: "p", text });
const list = (title, items) => ({ type: "list", title, items });
const check = (items) => ({ type: "checklist", items });
const price = (index) => packages[index].monthly.toLocaleString("sv-SE");

export const editorialPages = {
  "vad-kostar-en-hemsida": {
    title: "Vad kostar en hemsida? Jämför pris, innehåll och totalkostnad",
    description: "Räkna kostnaden för en hemsida, jämför offerter och se vad som ingår i Bas, Bredd och Spets. Kalkyl för startpris, månadspris och tillägg.",
    category: "Prisguide för hemsidor",
    summary: "Jämför kostnaden under samma period och för samma innehåll. Hos Stolt Marketing kostar en företagssajt från 1 190 kr/mån exkl moms med 0 kr start. Bas har upp till fem sidor och 12 månaders bindning. Fler tjänstesidor hör till Bredd eller Spets.",
    blocks: [
      h("Vad avgör priset på en hemsida?"),
      p("Antalet sidor, innehållsarbetet, funktionerna och ansvaret efter lansering styr priset. En enkel presentation, en sajt med många tjänster och en webbshop med affärssystem är tre olika uppdrag. Därför kan ett startpris inte jämföras utan att du vet vad som ingår."),
      p("Du kan bygga själv, anlita hjälp för ett engångsprojekt eller köpa en sajt med löpande drift. Inget alternativ är alltid billigast. Ett byggverktyg kan passa en liten verksamhet med tid och eget material. Ett projekt passar när du vill avgränsa bygget. Ett månadsupplägg fördelar kostnaden och gör ansvaret efter lansering tydligare."),
      { type: "compare", left: { title: "Ta med i jämförelsen", items: ["Startkostnad och minsta avtalsperiod", "Månadspris, drift och innehållsändringar", "Texter, bilder och produktinmatning", "Domän, licenser, betalning och frakt", "Överlämning och vad du äger"] }, right: { title: "Undvik att jämföra", items: ["Ett lockpris med en komplett leverans", "Fem sidor med ett större tjänstebibliotek", "En månadsavgift med ett helt projektpris", "Utseende med dokumenterad funktion", "Löften om fler kunder utan mätmetod"] } },
      h("Mina paket och kostnaden första året"),
      { type: "rows", items: packages.map((item) => ({ label: `${item.name}: ${item.monthly.toLocaleString("sv-SE")} kr/mån`, text: `${(item.monthly * 12).toLocaleString("sv-SE")} kr under 12 månader, exkl moms. 0 kr start.` })) },
      p("Bas omfattar upp till fem sidor. Bredd omfattar flera tjänster och obegränsat antal sidor inom den överenskomna företagssajten. Spets lägger till löpande innehåll, Google Ads-arbete och förfrågningsrutan. Annonsbudgeten betalas separat till Google. Efter första avtalets 12 månader löper hemsidan månadsvis."),
      p("En gratis presentation av det möjliga bygget är inte en färdig hel sajt. Du får ett klickbart förslag med startsida och en tjänstesida inom två arbetsdagar. Resten byggs efter ditt ja och enligt den omfattning vi har kommit överens om."),
      h("Räkna på samma tid och omfattning"),
      { type: "calculator", mode: "website" },
      p("Formeln är startkostnad plus månadspris gånger antal månader plus övriga kostnader under perioden. Räkna gärna på både 12 och 36 månader. Lägg till din egen tid separat om du jämför med att göra arbetet själv. Kalkylen ovan håller priserna konstanta; kontrollera om din offert medger prisjusteringar."),
      h("Tre exempel på rätt omfattning"),
      { type: "cards", items: [
        { title: "Enmansföretag med en tydlig tjänst", text: `Startsida, tjänst, om företaget, referenser och kontakt kan rymmas i Bas för ${price(0)} kr/mån. Fem bra sidor kan vara rätt omfattning. Det finns inget allmänt krav på 50 sidor för att synas i Google.` },
        { title: "Hantverksföretag med flera tjänster", text: `Tio till tjugo genomarbetade sidor hör till Bredd för ${price(1)} kr/mån. Sidorna ska motsvara verkliga tjänster och kundfrågor. Att upprepa samma text med nya ortsnamn tillför inte automatiskt värde.` },
        { title: "Företag som vill börja sälja online", text: "Webbshopstillägget är 800 kr/mån ovanpå valt hemsidepaket. Bas plus tillägget blir 1 990 kr/mån exkl moms. Produktmängd, betalsätt, frakt och integrationer avtalas före start. Större e-handelsprojekt med egna processer har en annan omfattning och en separat offert." },
      ] },
      h("Kostnader att kontrollera före ett ja"),
      p("Fråga om domän, webbhotell, säkerhet, uppdateringar, licenser och ändringar. För en webbshop tillkommer ofta betal- och fraktavgifter. För annonser behöver du en separat mediebudget. Nya integrationer och större ombyggnad kan ligga utanför ett löpande hemsidepaket. Det viktiga är att de beskrivs före start, inte först när behovet uppstår."),
      p("Be också om skillnaden mellan supportens svarstid och tiden tills en ändring är genomförd. I mina paket är innehållsändringar normalt klara inom två arbetsdagar i Bas och en arbetsdag i Bredd. Ett svar samma arbetsdag betyder inte att varje ny funktion blir klar samma dag."),
      h("Checklista för din offert"),
      check(["Jag vet vilka sidor och funktioner som ingår.", "Det är tydligt vem som skriver, fotograferar och lägger in material.", "Jag har räknat totalkostnaden för minst första avtalsperioden.", "Moms, bindning, uppsägning och externa avgifter framgår.", "Jag vet vad en innehållsändring och en ny funktion kostar.", "Ägande, åtkomst och överlämning står i avtalet.", "Formulär, mobilvy och viktiga länkar ingår i leveranskontrollen."]),
      h("När är en billigare sajt rätt val?"),
      p("När den löser den uppgift du faktiskt har. Om befintliga kunder bara behöver telefonnummer, öppettider och en presentation kan en enkel lösning räcka. Vill du presentera flera tjänster, mäta förfrågningar och förbättra innehåll över tid behöver du budget för det arbetet. Välj efter behov och ansvar, inte efter en föreställning om att högre pris alltid ger bättre ranking."),
    ],
    related: [{ title: "Jämför de aktuella paketen", href: "/priser" }, { title: "Be om ett gratis designförslag", href: "/hemsida-foretag#forslag" }, { title: "Vad kostar en större webbutik?", href: "/blogg/vad-kostar-webbutik" }],
    cta: { heading: "Få ett pris för det du behöver", text: "Berätta vilka tjänster sajten ska presentera och vad kunderna ska kunna göra. Jag återkommer med omfattning och pris.", href: "/boka?amne=pris", label: "Fråga om upplägg och pris" },
  },
  "vad-kostar-seo": {
    title: "Vad kostar SEO? Jämför arbetet och räkna på lönsamheten",
    description: "Förstå SEO-priset: analys, teknik, innehåll och uppföljning. Se mina fasta priser och räkna hur många extra uppdrag som behöver täcka kostnaden.",
    category: "Prisguide för SEO",
    summary: "SEO-priset beror på utgångsläge, konkurrens och överenskommet arbete. Hos Stolt Marketing kostar en avgränsad SEO-audit 4 900 kr exkl moms. Hemsidepaketet Spets kostar 2 990 kr/mån och omfattar löpande innehåll och SEO-arbete inom den avtalade sajten.",
    blocks: [
      h("Vad betalar du för när du köper SEO?"),
      p("Sökmotoroptimering består av tid för analys, tekniska rättningar, innehåll och uppföljning. Priset behöver beskriva vilka delar som faktiskt ingår. En rapport med förslag är inte samma leverans som att någon också genomför åtgärderna. Det är en vanlig anledning till att två offerter skiljer sig."),
      p("Det finns inget allmänt månadspris som gör ett erbjudande seriöst eller oseriöst. Ett begränsat uppdrag för ett lokalt företag kan vara mindre än ett arbete för en stor webbutik. Be om den konkreta omfattningen i stället för att dra slutsatser enbart av prisnivån."),
      h("Mina priser och deras avgränsningar"),
      { type: "rows", items: [{ label: "SEO-audit: 4 900 kr", text: "Engångsanalys av teknik, innehåll och synlighet med prioriterad åtgärdslista. Genomförande av åtgärder avtalas separat." }, { label: `Spets: ${price(2)} kr/mån`, text: "Hemsida, drift, löpande innehåll, SEO-arbete, förfrågningsrutan och skötsel av Google Ads inom den avtalade omfattningen. 12 månader, därefter månadsvis." }, { label: "Större eller särskilda behov", text: "Separat offert efter analys av sajtens omfattning, marknader och tekniska förutsättningar." }] },
      p("Alla belopp är exklusive moms. Spets är ett hemsidepaket med löpande arbete, inte ett obegränsat SEO-team för alla sajter och marknader. Annonsbudgeten till Google ingår inte i avgiften. Bas och Bredd lägger SEO-grunden men har inte samma löpande innehållsarbete som Spets."),
      h("Så blir två offerter jämförbara"),
      list("Be om svar på dessa frågor", ["Vilka sidor och sökfrågor prioriteras, och varför?", "Vilka analyser och tekniska rättningar görs först?", "Vem skriver och godkänner innehållet?", "Vad levereras och rapporteras varje månad?", "Ingår genomförande eller bara rekommendationer?", "Vilken bindning och uppsägning gäller?"]),
      p("Be också om åtkomst till din egen Search Console och mätning. En bra rapport visar vad som ändrats, vilka sökningar och sidor som påverkas och vad nästa steg är. Trafik utan relevanta förfrågningar behöver inte vara ett affärsresultat. Samtidigt kan förbättrat innehåll vara användbart innan det syns i en månads försäljning."),
      h("Omsättning är inte vinst"),
      p("Anta som räkneexempel att ett extra uppdrag ger 15 000 kr i intäkt exklusive moms och att 30 procent återstår efter rörliga kostnader. Det ger 4 500 kr att bidra till bland annat marknadsföring och fasta kostnader. Ett extra uppdrag skulle då täcka en SEO-avgift på 2 990 kr den månaden, men det bevisar inte att SEO har skapat uppdraget eller att hela företaget går med vinst."),
      { type: "calculator", mode: "seo" },
      p("Ändra värdena till ditt företag. Räkna med att arbetet kan kosta flera månader innan du ser effekt och att resultat kan variera med säsong, konkurrens och andra marknadsinsatser. Fördela inte automatiskt värdet av alla nya kunder till SEO bara för att de besökte hemsidan."),
      h("Engångsanalys eller löpande arbete?"),
      p("En audit passar när du vill veta vad som hindrar sajten och kunna ge en tydlig åtgärdslista till den som bygger. Löpande hjälp passar när prioriteringarna behöver följas upp och du vill att någon skriver, genomför och mäter över tid. Har du redan en tekniskt fungerande sajt kan en avgränsad insats vara rätt början."),
      h("Löften du bör undersöka närmare"),
      p("Ingen leverantör kan garantera en viss placering i Googles vanliga sökresultat. Be om förklaring om någon säljer hemliga metoder, stora länkpaket eller garanterad trafik utan tydlig källa. Resultatbaserad ersättning behöver definiera vad ett resultat är, hur det mäts och hur andra insatser hanteras. Det är avtalet och mätningen som måste granskas, inte bara namnet på modellen."),
      h("Checklista innan du beställer SEO"),
      check(["Jag har en nollmätning av relevanta sidor, sökningar och kontaktvägar.", "Jag vet vad som ingår i analys respektive genomförande.", "Jag har skriftlig omfattning, pris och avtalsperiod.", "Jag kan komma åt mina egna mätverktyg.", "Jag skiljer kontaktklick från förfrågningar, kunder och försäljning.", "Jag har räknat på marginal och tid till möjlig effekt."]),
    ],
    sources: [{ title: "Google: behöver du hjälp av en SEO?", href: "https://developers.google.com/search/docs/fundamentals/do-i-need-seo" }],
    related: [{ title: "Så fungerar sökmotoroptimering", href: "/sokmotoroptimering" }, { title: "Min SEO-tjänst och leverans", href: "/tjanster/seo" }, { title: "Jämför SEO-leverantörer", href: "/blogg/valja-seo-byra" }],
    cta: { heading: "Börja med rätt omfattning", text: "Vi går igenom vad du vill uppnå och om en audit eller löpande hjälp passar din sajt.", href: "/boka", label: "Boka en kostnadsfri genomgång" },
  },
  "sokmotoroptimering": {
    title: "Sökmotoroptimering: en praktisk guide till SEO",
    description: "Lär dig prioritera teknik, innehåll, lokal synlighet och mätning. En konkret SEO-guide för småföretag med checklista och källor från Google.",
    category: "Guide till sökmotoroptimering",
    summary: "SEO hjälper sökmotorer att hitta och förstå dina sidor och människor att få svar på sina frågor. Börja med att kontrollera indexering, förbättra dina viktigaste tjänstesidor och mäta riktiga kontaktvägar. Ingen sidmängd, teknisk poäng eller leverantör kan garantera en viss placering.",
    blocks: [
      h("Vad är sökmotoroptimering?"),
      p("Sökmotoroptimering, förkortat SEO, är arbetet med att förbättra en webbplats synlighet i de vanliga sökresultaten. Det omfattar teknik, innehåll och hur sajten länkas och presenteras. Du betalar inte sökmotorn för varje organiskt klick, men arbetet med sajten har en kostnad och behöver underhållas."),
      p("Målet för ett företag är att bli hittat vid relevanta frågor och hjälpa besökaren vidare. En rörmokare i Hässleholm behöver exempelvis svara på vilka VVS-arbeten företaget gör, var det arbetar, hur kunden får ett pris och hur kontakt går till. Att ranka på webbyrå Hässleholm skulle inte hjälpa samma kundresa."),
      h("Börja med sökfrågan och rätt sida"),
      p("Skriv ned vad kunden vill lösa före, under och efter ett köp. Jämför med sökfrågorna i Google Search Console och komplettera med sökordsdata när den finns. Volym är en uppskattning, inte ett facit. Även en ovanlig fråga kan vara affärsmässigt viktig om den handlar om precis den tjänst du säljer."),
      p("Välj sedan vilken befintlig sida som bäst svarar på frågan. En sida om pris har en annan uppgift än en sida där kunden bokar ett hembesök. Flera närliggande frågor kan ofta besvaras på samma sida. Skapa nya sidor när innehållet och behovet skiljer sig, inte för att fylla varje kombination av tjänst och ort."),
      h("Hur mycket innehåll behövs?"),
      p("Tillräckligt för att kunden ska förstå erbjudandet och fatta nästa beslut. Beskriv vad som ingår, arbetsområdet, processen, vad som påverkar priset och relevanta kundexempel. Det finns ingen generell regel om 1 500 ord eller minst 50 sidor. Fem välgjorda sidor kan passa ett litet företag; många tjänster kan kräva större omfattning."),
      p("En korrelation mellan stort sidantal och trafik visar inte att fler sidor ensamma orsakar bättre ranking. Större företag kan ha fler kunder, större kännedom och mer resurser. Upprepade ortssidor utan egna uppgifter hjälper sällan besökaren att välja rätt."),
      h("Gör sidans ämne tydligt"),
      list("En tjänstesida behöver ofta", ["En beskrivande titel och en tydlig huvudrubrik", "Ett direkt svar på vilken tjänst du erbjuder och var", "Underrubriker som delar upp kundens frågor", "Verkliga referenser, bilder eller andra relevanta bevis", "En begriplig nästa handling, exempelvis be om offert", "Länkar till pris, arbetsprocess och närliggande tjänster"]),
      p("Skriv naturligt och konkret. En titel kan innehålla tjänst och ort när båda behövs, men fyll inte alla rubriker med samma sökord. Google kan skriva om både titellänk och utdrag. En metabeskrivning bör sammanfatta sidans nytta; den är inte en garanti för vad som visas."),
      h("Kontrollera tekniken innan du producerar fler sidor"),
      p("Börja med att viktiga sidor svarar, går att nå via vanliga länkar och inte oavsiktligt har noindex. Använd URL-inspektionen i Search Console för att se indexeringsstatus. Sitemapen hjälper Google hitta adresser men garanterar inte att varje sida indexeras."),
      p("En canonical-adress anger vilken version av likartat innehåll du föredrar. Ett felaktigt standardvärde som pekar alla undersidor till startsidan kan få Google att välja fel version. Det betyder inte automatiskt att hela sajten försvinner, men det är ett fel värt att kontrollera. Viktigt innehåll ska också finnas tillgängligt för sökmotorn och kunna användas utan trasiga skript."),
      p("Testa mobilen, formulären och laddningen. Core Web Vitals mäter bland annat laddning, interaktion och layoutstabilitet. Ett enskilt Lighthouse-test är ett laboratorietest, medan fältdata beskriver verkliga användares upplevelse. En hög poäng är värdefull för felsökning men är inget rankinglöfte."),
      h("Lokal SEO och Google Företagsprofil"),
      p("Lokala resultat påverkas bland annat av relevans, avstånd och hur välkänt företaget är. Håll namn, kontaktuppgifter, kategorier, öppettider och arbetsområde korrekta i Google Företagsprofil. Påstå inte att du har kontor på en ort om verksamheten egentligen utgår från en annan plats."),
      p("Be kunder om ärliga omdömen på ett konsekvent sätt, inte bara dem du tror ger högt betyg. Erbjud inte belöning för Google-recensioner. Det finns ingen allmän tröskel på åtta eller 107 omdömen och inget betyg som garanterar en viss placering. Fortsätt svara på kundfeedback även efter att din profil har många recensioner."),
      h("Länkar, förtroende och AI-svar"),
      p("Relevanta länkar och omnämnanden kan hjälpa människor och sökmotorer att hitta och förstå företaget. Antalet hänvisande domäner är ett analysmått, inte ett universellt inträdeskrav. Köpta länkar som syftar till att manipulera ranking kan strida mot Googles spamregler."),
      p("Samma grundarbete är användbart när Google visar AI-funktioner. Google beskriver att flera relaterade sökningar kan användas för att hitta stödjande sidor. Det finns inget generellt krav på en topp-tio-placering eller särskild AI-märkning. Sakliga uppgifter, tydlig avsändare, indexerbart innehåll och uppdaterade källor är en bättre utgångspunkt än löften om garanterade AI-citat."),
      h("Mät det du vill förbättra"),
      p("Spara ett utgångsläge i Search Console: sökfrågor, sidor, visningar och klick under en bestämd period. Följ också de kontaktvägar som är viktiga för företaget. Ett telefonklick är inte ett genomfört samtal. Ett formulärinskick är inte samma sak som en ny kund. Koppla därför ihop webbstatistik med uppföljningen av faktiska förfrågningar."),
      p("Jämför likvärdiga perioder och ta hänsyn till säsong, annonser, ombyggnader och ändringar i mätningen. Annotera vad du har gjort. En förändring efter en redigering kan vara intressant utan att bevisa att just redigeringen orsakade utfallet."),
      h("Hur lång tid tar det och vad kostar det?"),
      p("Vissa tekniska rättningar kan märkas relativt snabbt, medan innehåll och konkurrensutsatta sökfrågor kan kräva månader av arbete. Det finns ingen säker tid till en placering eller en affär. Välj en leverans som du kan följa upp och en budget som verksamheten klarar även innan resultatet kommer."),
      p(`Hos mig kostar en avgränsad SEO-audit 4 900 kr exkl moms. Löpande innehåll och SEO-arbete inom hemsidepaketet Spets ingår i ${price(2)} kr/mån med 12 månaders bindning, därefter månadsvis. Mer omfattande behov kräver en egen offert. Börja gärna själv med checklistan nedan.`),
      h("Checklista för att komma igång"),
      check(["Öppna Search Console och kontrollera dina viktigaste sidors indexering.", "Välj tre relevanta kundfrågor och vilken sida som ska besvara varje fråga.", "Förbättra en befintlig tjänstesida med konkret omfattning, prisförklaring och kontaktväg.", "Kontrollera titel, huvudrubrik, interna länkar och canonical.", "Testa sidan och formuläret på en riktig mobil.", "Uppdatera Google Företagsprofil och be kunder om ärliga omdömen.", "Spara en daterad nollmätning och bestäm när du följer upp den."]),
    ],
    sources: [
      { title: "Google: grundläggande SEO-guide", href: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide" },
      { title: "Google: AI-funktioner och din webbplats", href: "https://developers.google.com/search/docs/appearance/ai-features" },
      { title: "Google: hur lokala resultat bestäms", href: "https://support.google.com/business/answer/7091?hl=sv" },
      { title: "Google: policy för recensioner och annat innehåll", href: "https://support.google.com/contributionpolicy/answer/7400114?hl=sv" },
      { title: "Web.dev: gränsvärden för Core Web Vitals", href: "https://web.dev/articles/defining-core-web-vitals-thresholds" },
    ],
    related: [{ title: "Gör en SEO-analys själv", href: "/blogg/seo-analys-sjalv" }, { title: "Vad kostar SEO?", href: "/vad-kostar-seo" }, { title: "Läs om min SEO-tjänst", href: "/tjanster/seo" }],
    cta: { heading: "Få hjälp att prioritera", text: "Boka en första genomgång om du vill diskutera vad som är värt att förbättra på din sajt. En full SEO-audit är ett separat uppdrag.", href: "/boka", label: "Boka en kostnadsfri genomgång" },
  },
};
